version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      database:
        condition: service_healthy # תלות בבריאות מסד הנתונים
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: secret
      DATABASE_NAME: flightdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: flightdb
    ports:
      - "5433:5432" # פורט חיצוני 5433, פנימי 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d flightdb"]
      interval: 5s
      timeout: 5s
      retries: 5
